TRAINING_DATA = {
    "Food & Dining": [
        "swiggy food order",
        "zomato restaurant order",
        "restaurant bill",
        "cafe payment",
        "coffee shop",
        "test coffee shop",
        "coffee shop payment",
        "pizza delivery",
        "food delivery",
        "mcdonalds",
        "kfc restaurant",
        "starbucks coffee",
        "bakery purchase",
        "dinner at restaurant",
        "grocery mart",
        "grocery store",
        "demo grocery mart",
        "supermarket purchase",
        "food purchase",
        "restaurant payment",
    ],

    "Travel & Transport": [
        "uber ride",
        "ola cab",
        "rapido ride",
        "metro ticket",
        "bus ticket",
        "irctc train ticket",
        "flight booking",
        "airline ticket",
        "airport taxi",
        "petrol station",
        "fuel purchase",
        "parking fee",
        "toll payment",
        "taxi payment",
        "cab fare",
        "transport payment",
    ],

    "Shopping": [
        "amazon purchase",
        "amazon online purchase",
        "amzn marketplace purchase",
        "flipkart order",
        "myntra purchase",
        "meesho order",
        "ajio shopping",
        "online shopping",
        "clothing purchase",
        "electronics purchase",
        "retail store",
        "mall purchase",
        "online retailer",
        "shopping payment",
        "demo retailer",
        "refund from retailer",
        "retail purchase",
        "store purchase",
    ],

    "Rent & Housing": [
        "monthly rent",
        "house rent payment",
        "apartment rent",
        "rental payment",
        "landlord payment",
        "home rental",
        "rent transfer",
        "monthly apartment rent",
        "demo rent holdings",
        "rent holdings payment",
        "housing rent",
        "monthly house rent",
    ],

    "Utilities": [
        "electricity bill",
        "electricity payment",
        "electric bill payment",
        "fictional electric company",
        "fictional electric co",
        "electric company payment",
        "water bill",
        "internet bill",
        "broadband payment",
        "wifi bill",
        "mobile recharge",
        "gas bill",
        "lpg payment",
        "utility bill",
        "phone bill",
        "power bill",
        "electricity company",
    ],

    "Entertainment": [
        "netflix subscription",
        "spotify subscription",
        "prime video",
        "disney plus subscription",
        "youtube premium",
        "movie ticket",
        "cinema ticket",
        "theatre ticket",
        "bookmyshow",
        "gaming subscription",
        "music subscription",
        "streaming subscription",
        "streaming service",
        "streaming svc",
        "placeholder streaming service",
        "placeholder streaming svc",
        "monthly streaming payment",
        "online streaming payment",
        "video streaming",
    ],

    "Health & Fitness": [
        "pharmacy purchase",
        "medicine purchase",
        "hospital payment",
        "doctor consultation",
        "clinic payment",
        "medical bill",
        "apollo pharmacy",
        "gym membership",
        "fitness membership",
        "health checkup",
        "medical store",
        "gym payment",
        "fictional gym membership",
        "gym membership payment",
        "fitness center payment",
    ],

    "Salary & Income": [
        "salary credit",
        "monthly salary",
        "salary payment",
        "payroll credit",
        "employee salary",
        "salary deposit",
        "monthly payroll",
        "salary transfer",
        "stipend payment",
        "income credit",
        "employer payment",
        "salary received",
        "sample employer payroll",
        "sample employer payroll co",
        "payroll deposit",
        "monthly income",
    ],

    "Others": [
        "cash withdrawal",
        "atm withdrawal",
        "atm withdrawal sample branch",
        "cash withdrawal from atm",
        "bank charge",
        "service charge",
        "insurance premium",
        "insurance payment",
        "sample insurance company",
        "sample insurance co",
        "insurance company payment",
        "savings transfer",
        "bank transfer",
        "transfer to savings",
        "online transfer to savings",
        "miscellaneous payment",
        "unknown payment",
        "annual fee",
        "account charge",
    ],
}